services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres_order:
    image: postgres:latest
    environment:
      POSTGRES_USER: order
      POSTGRES_PASSWORD: s3cr3t
      POSTGRES_DB: order
    ports:
      - "5434:5432"

  postgres_shipping:
    image: postgres:latest
    environment:
      POSTGRES_USER: shipping
      POSTGRES_PASSWORD: s3cr3t
      POSTGRES_DB: shipping
    ports:
      - "5435:5432"

  postgres_inventory:
    image: postgres:latest
    environment:
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: s3cr3t
      POSTGRES_DB: inventory
    ports:
      - "5436:5432"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    ports:
      - "8080:8080"
