name: Build
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghrc.io
  REPO_OWNER: ${{ github.repository_owner }}

jobs:
  build:
    strategy:
      matrix:
        image_name: ["order", "shipping", "inventory"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java with Corretto
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "corretto"

      - name: Build Jar
        working-directory: ${{ matrix.image_name }}
        run: |
          ./gradlew bootJar

      - name: Move Jar File
        working-directory: ${{ matrix.image_name }}
        run: |
          mv build/libs/*.jar app.jar

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract image metadata for ${{ matrix.image_name }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ matrix.image_name }}:latest

      - name: Build and push ${{ matrix.image_name }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.image_name }}
          file: ${{ matrix.image_name }}/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ matrix.image_name }}:latest
          labels: ${{ steps.meta.outputs.labels }}
